apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apt-cache

resources:
- ../../base

replicas:
- name: apt-cacher-ng
  count: 2

commonLabels:
  app.kubernetes.io/environment: production
