apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apt-cache

resources:
- ../../base

patches:
- path: service-patch.yaml
  target:
    kind: Service
    name: apt-cacher-ng

replicas:
- count: 2
  name: apt-cacher-ng

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/environment: production
