apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apt-cacher-ng-git
  namespace: argocd
  labels:
    app.kubernetes.io/name: apt-cacher-ng
spec:
  destination:
    namespace: apt-cache
    server: https://kubernetes.default.svc
  source:
    path: overlays/prod
    repoURL: https://github.com/zinntikumugai/apt-cache-apps.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
