apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apt-cache

resources:
- namespace.yaml
- configmap.yaml
- statefulset.yaml
- service.yaml
- pdb.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: cache-server
