apiVersion: v1
kind: Service
metadata:
  name: apt-cacher-ng
  namespace: apt-cache
  labels:
    app.kubernetes.io/name: apt-cacher-ng
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.0.10
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 3142
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: apt-cacher-ng
